name: Oireachta CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable Corepack
        run: corepack enable

      - name: Use Yarn 4.9.4
        run: corepack prepare yarn@4.9.4 --activate

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn check-lint

      - name: Run TypeScript type checking
        run: yarn check-types

      - name: Run tests
        run: yarn test:run
